/* empty css                      */import{S as v,a as w,i}from"./assets/vendor-CsWjCmIl.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const d=document.querySelector(".gallery");let S=new v(".gallery a",{captionsData:"alt",captionDelay:250});function u(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:c,comments:b,downloads:L})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${c}</p>
          <p><b>Comments</b> ${b}</p>
          <p><b>Downloads</b> ${L}</p>
        </div>
      </li>
    `).join("");d.insertAdjacentHTML("beforeend",t),S.refresh()}function q(){d.innerHTML=""}function p(){document.querySelector(".loader").classList.remove("hidden")}function f(){document.querySelector(".loader").classList.add("hidden")}function m(){document.querySelector(".load-more").classList.remove("hidden")}function h(){document.querySelector(".load-more").classList.add("hidden")}const R="51603629-b4647d91657d34a62103fca40",P="https://pixabay.com/api/",E=15;async function g(r,t){const s={key:R,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page:t};return(await w.get(P,{params:s})).data}const B=document.querySelector(".form"),$=document.querySelector(".load-more");document.querySelector(".gallery");let l="",n=1;const y=15;B.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),!l){i.warning({message:"Please enter a search query.",position:"topRight"});return}n=1,q(),h(),p();try{const t=await g(l,n);if(t.hits.length===0){i.info({message:"No images found.",position:"topRight"});return}u(t.hits),n*y>=t.totalHits?i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):m()}catch{i.error({message:"Something went wrong.",position:"topRight"})}finally{f()}});$.addEventListener("click",async()=>{n++,h(),p();try{const r=await g(l,n);if(r.hits.length===0){i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}u(r.hits);const t=document.querySelector(".gallery-item");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}n*y>=r.totalHits?i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):m()}catch{i.error({message:"Error loading more images.",position:"topRight"})}finally{f()}});
//# sourceMappingURL=index.js.map
