/* empty css                      */import{S as w,a as v,i as s}from"./assets/vendor-CsWjCmIl.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const d=document.querySelector(".gallery");let S=new w(".gallery a",{captionsData:"alt",captionDelay:250});function u(r){const t=r.map(({webformatURL:n,largeImageURL:a,tags:e,likes:o,views:c,comments:b,downloads:L})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${n}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${c}</p>
          <p><b>Comments</b> ${b}</p>
          <p><b>Downloads</b> ${L}</p>
        </div>
      </li>
    `).join("");d.insertAdjacentHTML("beforeend",t),S.refresh()}function q(){d.innerHTML=""}function p(){document.querySelector(".loader").classList.remove("hidden")}function m(){document.querySelector(".loader").classList.add("hidden")}function f(){document.querySelector(".load-more").classList.remove("hidden")}function g(){document.querySelector(".load-more").classList.add("hidden")}const P="51603629-b4647d91657d34a62103fca40",R="https://pixabay.com/api/",E=15;async function h(r,t){const n={key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page:t};return(await v.get(R,{params:n})).data}const B=document.querySelector(".form"),$=document.querySelector(".load-more"),M=document.querySelector(".gallery");let l="",i=1;const y=15;B.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),!l){s.warning({message:"Please enter a search query.",position:"topRight"});return}i=1,q(),g(),p();try{const t=await h(l,i);if(t.hits.length===0){s.info({message:"No images found.",position:"topRight"});return}u(t.hits),i*y>=t.totalHits?s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):f()}catch{s.error({message:"Something went wrong.",position:"topRight"})}finally{m()}});$.addEventListener("click",async()=>{i++,g(),p();try{const r=await h(l,i);u(r.hits);const t=M.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),i*y>=r.totalHits?s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):f()}catch{s.error({message:"Error loading more images.",position:"topRight"})}finally{m()}});
//# sourceMappingURL=index.js.map
