/* empty css                      */import{S as q,a as S,i as c}from"./assets/vendor-CsWjCmIl.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const f=document.querySelector(".gallery");let v=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const t=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:a,comments:n,downloads:u})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${a}</p>
          <p><b>Comments</b> ${n}</p>
          <p><b>Downloads</b> ${u}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),v.refresh()}function P(){f.innerHTML=""}function h(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function y(){document.querySelector(".load-more").classList.remove("hidden")}function L(){document.querySelector(".load-more").classList.add("hidden")}const E="51603629-b4647d91657d34a62103fca40",A="https://pixabay.com/api/",R=15;async function b(r,t){const s={key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:R,page:t};return(await S.get(A,{params:s})).data}const M=document.querySelector(".form"),O=document.querySelector(".load-more"),$=document.querySelector(".gallery");let d="",l=1;const w=15;M.addEventListener("submit",async r=>{if(r.preventDefault(),d=r.target.elements["search-text"].value.trim(),!d){c.warning({message:"Please enter a search query.",position:"topRight"});return}l=1,P(),L(),h();try{const t=await b(d,l);if(t.hits.length===0){c.info({message:"No images found.",position:"topRight"});return}p(t.hits),l*w>=t.totalHits?c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):y()}catch{c.error({message:"Something went wrong.",position:"topRight"})}finally{g()}});O.addEventListener("click",async()=>{l++,L(),h();try{const r=await b(d,l);p(r.hits),await new Promise(s=>requestAnimationFrame(s));const t=$.lastElementChild;t&&T(t.offsetTop-100,200),l*w>=r.totalHits?c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):y()}catch{c.error({message:"Error loading more images.",position:"topRight"})}finally{g()}});function T(r,t){const s=window.scrollY,i=r-s;let e=null;function o(n){e||(e=n);const u=n-e,m=Math.min(u/t,1);window.scrollTo(0,s+i*a(m)),m<1&&requestAnimationFrame(o)}function a(n){return n<.5?2*n*n:-1+(4-2*n)*n}requestAnimationFrame(o)}
//# sourceMappingURL=index.js.map
